dist: trusty
sudo: required

services:
  - docker

env:
  matrix:
  - TEST_TARGET: test-debian
  - TEST_TARGET: test-alpine

before_install:
  - docker version
  - docker info
  # prepare docker test requirements
  - make update-dependencies

script:
  - make $TEST_TARGET
